CREATE TABLE task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  start_date DATE,
  due_date DATE,
  `condition` VARCHAR(128),
  memo TEXT,
  status INT, -- 0=未着手, 1=進行中, 2=完了
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);